### ISSUE TITLE
[Bug] Server crashes on shutdown/reboot

### ISSUE THREAD

**Issue by some-username-here1** [Mentrillum/Slender-Fortress-Modified-Versions#23]
As the title says, a server of mine that I've been working on crashes whenever the gamemode is currently on SF2 Modified and gets shutdown or reboots. I have no idea why it happens since I don't have a ton of other plugins installed, besides Deathrun Redux and the required plugins for it.

Even then, I have [Plugin Enable / Disable](https://forums.alliedmods.net/showthread.php?p=1682844) and [Map Configs with Prefix Support](https://forums.alliedmods.net/showthread.php?t=69506) installed that would unload and disable any other plugins when the server is on a map with a specific prefix.

EDIT: If crash dumps are needed, I can link to my dumps provided by Accelerator.

**Comment by Mentrillum** [comment]
You might want to provide both a crash log and if possible a error log since someone else had an issue with loading SF2M because the SteamWorks method I implemented back in 1.6.02 was busted and prevented any loading, since then has been fixed in 1.6.03.

**Comment by some-username-here1** [comment]
I currently have 1.6.03 installed, with a plugin included with SteamWorks that converts SteamTools calls into SteamWorks calls.

Also does this count for a crash dump?
https://crash.limetech.org/xarl75jxvlas

Apologies if it's the wrong one, I'm on mobile right now

**Comment by Mentrillum** [comment]
If I had to guess the plugin that converts SteamTools calls to SteamWorks calls wouldn't work well with SF2M, you can have SteamWorks or SteamTools or both if you wanted to, however I am not sure if modifying SteamTools calls to SteamWorks calls would crash the server while SF2M is running, so whenever you get the chance, would it be possible you can provide a link to the call converter plugin just to clarify its not that plugin thats causing the crashes? Both Plugin Enable / Disable and Map Configs with Prefix Support should not impact the plugin so heavily just so you know.

**Comment by some-username-here1** [comment]
Here's a link to it, it was originally `swag.sp` before renaming and compiling it

https://forums.alliedmods.net/showthread.php?t=229556

**Comment by some-username-here1** [comment]
Also even if I unload the plugin that translate the calls before running "quit", the server still crashes

**Comment by Mentrillum** [comment]
Unable to replicate the glitch/bug with the builds all SF2M servers have, and I cannot pick up the recent recent build from June since there is no Windows build I can test out. The SF2M tutorial uses the following builds rather than the builds you sent, even the single Linux user used these builds and their server didn't crash, so if you can try these builds to see if it will make a difference, that'd be appreciated.

https://users.alliedmods.net/~kyles/builds/SteamWorks/

**Comment by some-username-here1** [comment]
that's the one I already had installed, but it's still crashing

**Comment by some-username-here1** [comment]
So I backed up my current addons folder, installed sourcemod and metamod fresh, followed by the plugins for sf2m and sf2m itself, and it ended up still crashing. I'm not sure why though

**Comment by Mentrillum** [comment]
This will be really difficult, but I'll see if I can look into this problem on my end to see how to not only replicate this crash on my end but also how to fix it. The person who got a similar issue where SF2M wouldn't load was back in 1.6.02, after upgrading to a patch for 1.6.02 and above, this issue was no longer present. Also a small side note, if you are using Sourcemod 1.11 or 1.9, be aware SF2M is really unstable on those two Sourcemod versions, but I can only assume you're using Sourcemod 1.10.

**Comment by some-username-here1** [comment]
If it'll help, I can provide you an archive of my sf2m install with accelerator included (although it hasn't been working for a while for some reason)

**Comment by some-username-here1** [comment]
Any progress on this by any chance? I haven't tested it out with the latest version of sf2m yet, but if you want me to; let me know.

**Comment by Mentrillum** [comment]
So 1.6.06, 1.6.06 Dev 1, and 1.6.06 Dev 2 are very unstable at the moment, it actually caused one of the official servers to crash often, currently 4 plugins can crash the server if SF2M is installed, those are Roll the Dice, Emotes, Stamm, and Gravestone Markers. Once they took the more stable 1.6.07 Indev, the crashes stopped, so we'll just have to wait until that version comes out. If you have nothing but the required plugins + extensions for SF2M and the default plugins + extensions found in Sourcemod's installation, this may be the issue.

**Comment by some-username-here1** [comment]
I don't have any of those plugins on my server, and I'll have to try manually restarting my server with the SF2M gamemode enabled to see if it has fixed itself or not. I moved the servers I have onto better hardware

**Comment by some-username-here1** [comment]
After upgrading SF2M to 1.6.1 Pre-release 1, it's now starting to crash more often than it should.

**Comment by Mentrillum** [comment]
Unable to replicate bug.
